command_timeout = 750

[aws]
disabled = true

[hostname]
disabled = false
ssh_only = false
format = "âŸª[$hostname](#5a91bf)âŸ« "
trim_at = ".mitre.org"

[jobs]
disabled = false
symbol = "&"
threshold = 1

[time]
disabled = false
format = "[$time](#ff884d) "

[directory]
disabled = false
style = "#39ac39"

[git_branch]
disabled = false
always_show_remote = false
style = "#c44dff"

[python]
disabled = false
symbol = "ğŸ "
pyenv_version_name = false
style = "#0092cc"

[rlang]
disabled = true

[java]
disabled = true
style = "#0092cc"

[docker_context]
disabled = true

[nodejs]
disabled = false

[rust]
format = 'via [âš™ï¸ $version](red bold)'
